# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-27 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('memberlevel', models.IntegerField()),
                ('regdate', models.DateTimeField()),
                ('lastlogin', models.DateTimeField()),
                ('blocked', models.IntegerField()),
                ('activated', models.IntegerField()),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolApplyNumber',
            fields=[
                ('school_id', models.IntegerField(db_column='School_ID', primary_key=True, serialize=False)),
                ('apply_num', models.IntegerField(db_column='Apply_num')),
            ],
            options={
                'db_table': 'school_apply_number',
                'managed': False,
            },
        ),
    ]
